//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAESDO.Catbert.Test.CatbertService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceUser", Namespace="CAESDO.Services")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CAESDO.Catbert.Test.CatbertService.CatbertUser))]
    public partial class ServiceUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatbertUser", Namespace="CAESDO.Services")]
    [System.SerializableAttribute()]
    public partial class CatbertUser : CAESDO.Catbert.Test.CatbertService.ServiceUser {
        
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CAESDO.Catbert.Test.CatbertService.ServiceRole[] RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CAESDO.Catbert.Test.CatbertService.ServiceUnit[] UnitsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public CAESDO.Catbert.Test.CatbertService.ServiceRole[] Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CAESDO.Catbert.Test.CatbertService.ServiceUnit[] Units {
            get {
                return this.UnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitsField, value) != true)) {
                    this.UnitsField = value;
                    this.RaisePropertyChanged("Units");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceRole", Namespace="CAESDO.Services")]
    [System.SerializableAttribute()]
    public partial class ServiceRole : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceUnit", Namespace="CAESDO.Services")]
    [System.SerializableAttribute()]
    public partial class ServiceUnit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitFISField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UnitFIS {
            get {
                return this.UnitFISField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitFISField, value) != true)) {
                    this.UnitFISField = value;
                    this.RaisePropertyChanged("UnitFIS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="CAESDO.Services", ConfigurationName="CatbertService.CatbertWebServiceSoap")]
    public interface CatbertWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name eid from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/SearchNewUser", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.SearchNewUserResponse SearchNewUser(CAESDO.Catbert.Test.CatbertService.SearchNewUserRequest request);
        
        // CODEGEN: Generating message contract since element name serviceUser from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/InsertNewUser", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.InsertNewUserResponse InsertNewUser(CAESDO.Catbert.Test.CatbertService.InsertNewUserRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/VerifyUser", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.VerifyUserResponse VerifyUser(CAESDO.Catbert.Test.CatbertService.VerifyUserRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetUser", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.GetUserResponse GetUser(CAESDO.Catbert.Test.CatbertService.GetUserRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/AssignPermissions", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.AssignPermissionsResponse AssignPermissions(CAESDO.Catbert.Test.CatbertService.AssignPermissionsRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/DeletePermissions", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.DeletePermissionsResponse DeletePermissions(CAESDO.Catbert.Test.CatbertService.DeletePermissionsRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/PermissionExists", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.PermissionExistsResponse PermissionExists(CAESDO.Catbert.Test.CatbertService.PermissionExistsRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/AddUnit", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.AddUnitResponse AddUnit(CAESDO.Catbert.Test.CatbertService.AddUnitRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/DeleteUnit", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.DeleteUnitResponse DeleteUnit(CAESDO.Catbert.Test.CatbertService.DeleteUnitRequest request);
        
        // CODEGEN: Generating message contract since element name GetUnitsResult from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetUnits", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.GetUnitsResponse GetUnits(CAESDO.Catbert.Test.CatbertService.GetUnitsRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetUnitsByUser", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.GetUnitsByUserResponse GetUnitsByUser(CAESDO.Catbert.Test.CatbertService.GetUnitsByUserRequest request);
        
        // CODEGEN: Generating message contract since element name application from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetRoles", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.GetRolesResponse GetRoles(CAESDO.Catbert.Test.CatbertService.GetRolesRequest request);
        
        // CODEGEN: Generating message contract since element name application from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetRolesByUser", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.GetRolesByUserResponse GetRolesByUser(CAESDO.Catbert.Test.CatbertService.GetRolesByUserRequest request);
        
        // CODEGEN: Generating message contract since element name application from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetUsersByApplication", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationResponse GetUsersByApplication(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRequest request);
        
        // CODEGEN: Generating message contract since element name application from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetUsersByApplicationRole", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleResponse GetUsersByApplicationRole(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/SetEmail", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.SetEmailResponse SetEmail(CAESDO.Catbert.Test.CatbertService.SetEmailRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace CAESDO.Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/SetPhoneNumber", ReplyAction="*")]
        CAESDO.Catbert.Test.CatbertService.SetPhoneNumberResponse SetPhoneNumber(CAESDO.Catbert.Test.CatbertService.SetPhoneNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchNewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchNewUser", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.SearchNewUserRequestBody Body;
        
        public SearchNewUserRequest() {
        }
        
        public SearchNewUserRequest(CAESDO.Catbert.Test.CatbertService.SearchNewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class SearchNewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string login;
        
        public SearchNewUserRequestBody() {
        }
        
        public SearchNewUserRequestBody(string eid, string firstName, string lastName, string login) {
            this.eid = eid;
            this.firstName = firstName;
            this.lastName = lastName;
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchNewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchNewUserResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.SearchNewUserResponseBody Body;
        
        public SearchNewUserResponse() {
        }
        
        public SearchNewUserResponse(CAESDO.Catbert.Test.CatbertService.SearchNewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class SearchNewUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CAESDO.Catbert.Test.CatbertService.ServiceUser[] SearchNewUserResult;
        
        public SearchNewUserResponseBody() {
        }
        
        public SearchNewUserResponseBody(CAESDO.Catbert.Test.CatbertService.ServiceUser[] SearchNewUserResult) {
            this.SearchNewUserResult = SearchNewUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNewUser", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.InsertNewUserRequestBody Body;
        
        public InsertNewUserRequest() {
        }
        
        public InsertNewUserRequest(CAESDO.Catbert.Test.CatbertService.InsertNewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class InsertNewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CAESDO.Catbert.Test.CatbertService.ServiceUser serviceUser;
        
        public InsertNewUserRequestBody() {
        }
        
        public InsertNewUserRequestBody(CAESDO.Catbert.Test.CatbertService.ServiceUser serviceUser) {
            this.serviceUser = serviceUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNewUserResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.InsertNewUserResponseBody Body;
        
        public InsertNewUserResponse() {
        }
        
        public InsertNewUserResponse(CAESDO.Catbert.Test.CatbertService.InsertNewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class InsertNewUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertNewUserResult;
        
        public InsertNewUserResponseBody() {
        }
        
        public InsertNewUserResponseBody(int InsertNewUserResult) {
            this.InsertNewUserResult = InsertNewUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyUser", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.VerifyUserRequestBody Body;
        
        public VerifyUserRequest() {
        }
        
        public VerifyUserRequest(CAESDO.Catbert.Test.CatbertService.VerifyUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class VerifyUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        public VerifyUserRequestBody() {
        }
        
        public VerifyUserRequestBody(string login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyUserResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.VerifyUserResponseBody Body;
        
        public VerifyUserResponse() {
        }
        
        public VerifyUserResponse(CAESDO.Catbert.Test.CatbertService.VerifyUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class VerifyUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyUserResult;
        
        public VerifyUserResponseBody() {
        }
        
        public VerifyUserResponseBody(bool VerifyUserResult) {
            this.VerifyUserResult = VerifyUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(CAESDO.Catbert.Test.CatbertService.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string application;
        
        public GetUserRequestBody() {
        }
        
        public GetUserRequestBody(string login, string application) {
            this.login = login;
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(CAESDO.Catbert.Test.CatbertService.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CAESDO.Catbert.Test.CatbertService.CatbertUser GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(CAESDO.Catbert.Test.CatbertService.CatbertUser GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssignPermissionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssignPermissions", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.AssignPermissionsRequestBody Body;
        
        public AssignPermissionsRequest() {
        }
        
        public AssignPermissionsRequest(CAESDO.Catbert.Test.CatbertService.AssignPermissionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class AssignPermissionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string application;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string role;
        
        public AssignPermissionsRequestBody() {
        }
        
        public AssignPermissionsRequestBody(string login, string application, string role) {
            this.login = login;
            this.application = application;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssignPermissionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssignPermissionsResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.AssignPermissionsResponseBody Body;
        
        public AssignPermissionsResponse() {
        }
        
        public AssignPermissionsResponse(CAESDO.Catbert.Test.CatbertService.AssignPermissionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class AssignPermissionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AssignPermissionsResult;
        
        public AssignPermissionsResponseBody() {
        }
        
        public AssignPermissionsResponseBody(bool AssignPermissionsResult) {
            this.AssignPermissionsResult = AssignPermissionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePermissionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePermissions", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.DeletePermissionsRequestBody Body;
        
        public DeletePermissionsRequest() {
        }
        
        public DeletePermissionsRequest(CAESDO.Catbert.Test.CatbertService.DeletePermissionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class DeletePermissionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string application;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string role;
        
        public DeletePermissionsRequestBody() {
        }
        
        public DeletePermissionsRequestBody(string login, string application, string role) {
            this.login = login;
            this.application = application;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePermissionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePermissionsResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.DeletePermissionsResponseBody Body;
        
        public DeletePermissionsResponse() {
        }
        
        public DeletePermissionsResponse(CAESDO.Catbert.Test.CatbertService.DeletePermissionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class DeletePermissionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeletePermissionsResult;
        
        public DeletePermissionsResponseBody() {
        }
        
        public DeletePermissionsResponseBody(bool DeletePermissionsResult) {
            this.DeletePermissionsResult = DeletePermissionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PermissionExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PermissionExists", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.PermissionExistsRequestBody Body;
        
        public PermissionExistsRequest() {
        }
        
        public PermissionExistsRequest(CAESDO.Catbert.Test.CatbertService.PermissionExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class PermissionExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string application;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string role;
        
        public PermissionExistsRequestBody() {
        }
        
        public PermissionExistsRequestBody(string login, string application, string role) {
            this.login = login;
            this.application = application;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PermissionExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PermissionExistsResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.PermissionExistsResponseBody Body;
        
        public PermissionExistsResponse() {
        }
        
        public PermissionExistsResponse(CAESDO.Catbert.Test.CatbertService.PermissionExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class PermissionExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PermissionExistsResult;
        
        public PermissionExistsResponseBody() {
        }
        
        public PermissionExistsResponseBody(bool PermissionExistsResult) {
            this.PermissionExistsResult = PermissionExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUnitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUnit", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.AddUnitRequestBody Body;
        
        public AddUnitRequest() {
        }
        
        public AddUnitRequest(CAESDO.Catbert.Test.CatbertService.AddUnitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class AddUnitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string unitFIS;
        
        public AddUnitRequestBody() {
        }
        
        public AddUnitRequestBody(string login, string unitFIS) {
            this.login = login;
            this.unitFIS = unitFIS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUnitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUnitResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.AddUnitResponseBody Body;
        
        public AddUnitResponse() {
        }
        
        public AddUnitResponse(CAESDO.Catbert.Test.CatbertService.AddUnitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class AddUnitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddUnitResult;
        
        public AddUnitResponseBody() {
        }
        
        public AddUnitResponseBody(bool AddUnitResult) {
            this.AddUnitResult = AddUnitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUnitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUnit", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.DeleteUnitRequestBody Body;
        
        public DeleteUnitRequest() {
        }
        
        public DeleteUnitRequest(CAESDO.Catbert.Test.CatbertService.DeleteUnitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class DeleteUnitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string unitFIS;
        
        public DeleteUnitRequestBody() {
        }
        
        public DeleteUnitRequestBody(string login, string unitFIS) {
            this.login = login;
            this.unitFIS = unitFIS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUnitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUnitResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.DeleteUnitResponseBody Body;
        
        public DeleteUnitResponse() {
        }
        
        public DeleteUnitResponse(CAESDO.Catbert.Test.CatbertService.DeleteUnitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class DeleteUnitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteUnitResult;
        
        public DeleteUnitResponseBody() {
        }
        
        public DeleteUnitResponseBody(bool DeleteUnitResult) {
            this.DeleteUnitResult = DeleteUnitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnits", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetUnitsRequestBody Body;
        
        public GetUnitsRequest() {
        }
        
        public GetUnitsRequest(CAESDO.Catbert.Test.CatbertService.GetUnitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUnitsRequestBody {
        
        public GetUnitsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnitsResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetUnitsResponseBody Body;
        
        public GetUnitsResponse() {
        }
        
        public GetUnitsResponse(CAESDO.Catbert.Test.CatbertService.GetUnitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetUnitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CAESDO.Catbert.Test.CatbertService.ServiceUnit[] GetUnitsResult;
        
        public GetUnitsResponseBody() {
        }
        
        public GetUnitsResponseBody(CAESDO.Catbert.Test.CatbertService.ServiceUnit[] GetUnitsResult) {
            this.GetUnitsResult = GetUnitsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnitsByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnitsByUser", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetUnitsByUserRequestBody Body;
        
        public GetUnitsByUserRequest() {
        }
        
        public GetUnitsByUserRequest(CAESDO.Catbert.Test.CatbertService.GetUnitsByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetUnitsByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        public GetUnitsByUserRequestBody() {
        }
        
        public GetUnitsByUserRequestBody(string login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnitsByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnitsByUserResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetUnitsByUserResponseBody Body;
        
        public GetUnitsByUserResponse() {
        }
        
        public GetUnitsByUserResponse(CAESDO.Catbert.Test.CatbertService.GetUnitsByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetUnitsByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CAESDO.Catbert.Test.CatbertService.ServiceUnit[] GetUnitsByUserResult;
        
        public GetUnitsByUserResponseBody() {
        }
        
        public GetUnitsByUserResponseBody(CAESDO.Catbert.Test.CatbertService.ServiceUnit[] GetUnitsByUserResult) {
            this.GetUnitsByUserResult = GetUnitsByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoles", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetRolesRequestBody Body;
        
        public GetRolesRequest() {
        }
        
        public GetRolesRequest(CAESDO.Catbert.Test.CatbertService.GetRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetRolesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string application;
        
        public GetRolesRequestBody() {
        }
        
        public GetRolesRequestBody(string application) {
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRolesResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetRolesResponseBody Body;
        
        public GetRolesResponse() {
        }
        
        public GetRolesResponse(CAESDO.Catbert.Test.CatbertService.GetRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CAESDO.Catbert.Test.CatbertService.ServiceRole[] GetRolesResult;
        
        public GetRolesResponseBody() {
        }
        
        public GetRolesResponseBody(CAESDO.Catbert.Test.CatbertService.ServiceRole[] GetRolesResult) {
            this.GetRolesResult = GetRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRolesByUser", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetRolesByUserRequestBody Body;
        
        public GetRolesByUserRequest() {
        }
        
        public GetRolesByUserRequest(CAESDO.Catbert.Test.CatbertService.GetRolesByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetRolesByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string application;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string login;
        
        public GetRolesByUserRequestBody() {
        }
        
        public GetRolesByUserRequestBody(string application, string login) {
            this.application = application;
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRolesByUserResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetRolesByUserResponseBody Body;
        
        public GetRolesByUserResponse() {
        }
        
        public GetRolesByUserResponse(CAESDO.Catbert.Test.CatbertService.GetRolesByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetRolesByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CAESDO.Catbert.Test.CatbertService.ServiceRole[] GetRolesByUserResult;
        
        public GetRolesByUserResponseBody() {
        }
        
        public GetRolesByUserResponseBody(CAESDO.Catbert.Test.CatbertService.ServiceRole[] GetRolesByUserResult) {
            this.GetRolesByUserResult = GetRolesByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersByApplicationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersByApplication", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRequestBody Body;
        
        public GetUsersByApplicationRequest() {
        }
        
        public GetUsersByApplicationRequest(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetUsersByApplicationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string application;
        
        public GetUsersByApplicationRequestBody() {
        }
        
        public GetUsersByApplicationRequestBody(string application) {
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersByApplicationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersByApplicationResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationResponseBody Body;
        
        public GetUsersByApplicationResponse() {
        }
        
        public GetUsersByApplicationResponse(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetUsersByApplicationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CAESDO.Catbert.Test.CatbertService.CatbertUser[] GetUsersByApplicationResult;
        
        public GetUsersByApplicationResponseBody() {
        }
        
        public GetUsersByApplicationResponseBody(CAESDO.Catbert.Test.CatbertService.CatbertUser[] GetUsersByApplicationResult) {
            this.GetUsersByApplicationResult = GetUsersByApplicationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersByApplicationRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersByApplicationRole", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleRequestBody Body;
        
        public GetUsersByApplicationRoleRequest() {
        }
        
        public GetUsersByApplicationRoleRequest(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetUsersByApplicationRoleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string application;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string role;
        
        public GetUsersByApplicationRoleRequestBody() {
        }
        
        public GetUsersByApplicationRoleRequestBody(string application, string role) {
            this.application = application;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersByApplicationRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersByApplicationRoleResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleResponseBody Body;
        
        public GetUsersByApplicationRoleResponse() {
        }
        
        public GetUsersByApplicationRoleResponse(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class GetUsersByApplicationRoleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CAESDO.Catbert.Test.CatbertService.CatbertUser[] GetUsersByApplicationRoleResult;
        
        public GetUsersByApplicationRoleResponseBody() {
        }
        
        public GetUsersByApplicationRoleResponseBody(CAESDO.Catbert.Test.CatbertService.CatbertUser[] GetUsersByApplicationRoleResult) {
            this.GetUsersByApplicationRoleResult = GetUsersByApplicationRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetEmail", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.SetEmailRequestBody Body;
        
        public SetEmailRequest() {
        }
        
        public SetEmailRequest(CAESDO.Catbert.Test.CatbertService.SetEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class SetEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string emailAddress;
        
        public SetEmailRequestBody() {
        }
        
        public SetEmailRequestBody(string login, string emailAddress) {
            this.login = login;
            this.emailAddress = emailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetEmailResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.SetEmailResponseBody Body;
        
        public SetEmailResponse() {
        }
        
        public SetEmailResponse(CAESDO.Catbert.Test.CatbertService.SetEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class SetEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetEmailResult;
        
        public SetEmailResponseBody() {
        }
        
        public SetEmailResponseBody(bool SetEmailResult) {
            this.SetEmailResult = SetEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPhoneNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPhoneNumber", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.SetPhoneNumberRequestBody Body;
        
        public SetPhoneNumberRequest() {
        }
        
        public SetPhoneNumberRequest(CAESDO.Catbert.Test.CatbertService.SetPhoneNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class SetPhoneNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phoneNumber;
        
        public SetPhoneNumberRequestBody() {
        }
        
        public SetPhoneNumberRequestBody(string login, string phoneNumber) {
            this.login = login;
            this.phoneNumber = phoneNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPhoneNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPhoneNumberResponse", Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.SetPhoneNumberResponseBody Body;
        
        public SetPhoneNumberResponse() {
        }
        
        public SetPhoneNumberResponse(CAESDO.Catbert.Test.CatbertService.SetPhoneNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="CAESDO.Services")]
    public partial class SetPhoneNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetPhoneNumberResult;
        
        public SetPhoneNumberResponseBody() {
        }
        
        public SetPhoneNumberResponseBody(bool SetPhoneNumberResult) {
            this.SetPhoneNumberResult = SetPhoneNumberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CatbertWebServiceSoapChannel : CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatbertWebServiceSoapClient : System.ServiceModel.ClientBase<CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap>, CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap {
        
        public CatbertWebServiceSoapClient() {
        }
        
        public CatbertWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatbertWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatbertWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatbertWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.SearchNewUserResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.SearchNewUser(CAESDO.Catbert.Test.CatbertService.SearchNewUserRequest request) {
            return base.Channel.SearchNewUser(request);
        }
        
        public CAESDO.Catbert.Test.CatbertService.ServiceUser[] SearchNewUser(string eid, string firstName, string lastName, string login) {
            CAESDO.Catbert.Test.CatbertService.SearchNewUserRequest inValue = new CAESDO.Catbert.Test.CatbertService.SearchNewUserRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.SearchNewUserRequestBody();
            inValue.Body.eid = eid;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.login = login;
            CAESDO.Catbert.Test.CatbertService.SearchNewUserResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).SearchNewUser(inValue);
            return retVal.Body.SearchNewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.InsertNewUserResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.InsertNewUser(CAESDO.Catbert.Test.CatbertService.InsertNewUserRequest request) {
            return base.Channel.InsertNewUser(request);
        }
        
        public int InsertNewUser(CAESDO.Catbert.Test.CatbertService.ServiceUser serviceUser) {
            CAESDO.Catbert.Test.CatbertService.InsertNewUserRequest inValue = new CAESDO.Catbert.Test.CatbertService.InsertNewUserRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.InsertNewUserRequestBody();
            inValue.Body.serviceUser = serviceUser;
            CAESDO.Catbert.Test.CatbertService.InsertNewUserResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).InsertNewUser(inValue);
            return retVal.Body.InsertNewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.VerifyUserResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.VerifyUser(CAESDO.Catbert.Test.CatbertService.VerifyUserRequest request) {
            return base.Channel.VerifyUser(request);
        }
        
        public bool VerifyUser(string login) {
            CAESDO.Catbert.Test.CatbertService.VerifyUserRequest inValue = new CAESDO.Catbert.Test.CatbertService.VerifyUserRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.VerifyUserRequestBody();
            inValue.Body.login = login;
            CAESDO.Catbert.Test.CatbertService.VerifyUserResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).VerifyUser(inValue);
            return retVal.Body.VerifyUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetUserResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetUser(CAESDO.Catbert.Test.CatbertService.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public CAESDO.Catbert.Test.CatbertService.CatbertUser GetUser(string login, string application) {
            CAESDO.Catbert.Test.CatbertService.GetUserRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetUserRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.GetUserRequestBody();
            inValue.Body.login = login;
            inValue.Body.application = application;
            CAESDO.Catbert.Test.CatbertService.GetUserResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetUser(inValue);
            return retVal.Body.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.AssignPermissionsResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.AssignPermissions(CAESDO.Catbert.Test.CatbertService.AssignPermissionsRequest request) {
            return base.Channel.AssignPermissions(request);
        }
        
        public bool AssignPermissions(string login, string application, string role) {
            CAESDO.Catbert.Test.CatbertService.AssignPermissionsRequest inValue = new CAESDO.Catbert.Test.CatbertService.AssignPermissionsRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.AssignPermissionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.application = application;
            inValue.Body.role = role;
            CAESDO.Catbert.Test.CatbertService.AssignPermissionsResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).AssignPermissions(inValue);
            return retVal.Body.AssignPermissionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.DeletePermissionsResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.DeletePermissions(CAESDO.Catbert.Test.CatbertService.DeletePermissionsRequest request) {
            return base.Channel.DeletePermissions(request);
        }
        
        public bool DeletePermissions(string login, string application, string role) {
            CAESDO.Catbert.Test.CatbertService.DeletePermissionsRequest inValue = new CAESDO.Catbert.Test.CatbertService.DeletePermissionsRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.DeletePermissionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.application = application;
            inValue.Body.role = role;
            CAESDO.Catbert.Test.CatbertService.DeletePermissionsResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).DeletePermissions(inValue);
            return retVal.Body.DeletePermissionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.PermissionExistsResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.PermissionExists(CAESDO.Catbert.Test.CatbertService.PermissionExistsRequest request) {
            return base.Channel.PermissionExists(request);
        }
        
        public bool PermissionExists(string login, string application, string role) {
            CAESDO.Catbert.Test.CatbertService.PermissionExistsRequest inValue = new CAESDO.Catbert.Test.CatbertService.PermissionExistsRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.PermissionExistsRequestBody();
            inValue.Body.login = login;
            inValue.Body.application = application;
            inValue.Body.role = role;
            CAESDO.Catbert.Test.CatbertService.PermissionExistsResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).PermissionExists(inValue);
            return retVal.Body.PermissionExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.AddUnitResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.AddUnit(CAESDO.Catbert.Test.CatbertService.AddUnitRequest request) {
            return base.Channel.AddUnit(request);
        }
        
        public bool AddUnit(string login, string unitFIS) {
            CAESDO.Catbert.Test.CatbertService.AddUnitRequest inValue = new CAESDO.Catbert.Test.CatbertService.AddUnitRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.AddUnitRequestBody();
            inValue.Body.login = login;
            inValue.Body.unitFIS = unitFIS;
            CAESDO.Catbert.Test.CatbertService.AddUnitResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).AddUnit(inValue);
            return retVal.Body.AddUnitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.DeleteUnitResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.DeleteUnit(CAESDO.Catbert.Test.CatbertService.DeleteUnitRequest request) {
            return base.Channel.DeleteUnit(request);
        }
        
        public bool DeleteUnit(string login, string unitFIS) {
            CAESDO.Catbert.Test.CatbertService.DeleteUnitRequest inValue = new CAESDO.Catbert.Test.CatbertService.DeleteUnitRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.DeleteUnitRequestBody();
            inValue.Body.login = login;
            inValue.Body.unitFIS = unitFIS;
            CAESDO.Catbert.Test.CatbertService.DeleteUnitResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).DeleteUnit(inValue);
            return retVal.Body.DeleteUnitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetUnitsResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetUnits(CAESDO.Catbert.Test.CatbertService.GetUnitsRequest request) {
            return base.Channel.GetUnits(request);
        }
        
        public CAESDO.Catbert.Test.CatbertService.ServiceUnit[] GetUnits() {
            CAESDO.Catbert.Test.CatbertService.GetUnitsRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetUnitsRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.GetUnitsRequestBody();
            CAESDO.Catbert.Test.CatbertService.GetUnitsResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetUnits(inValue);
            return retVal.Body.GetUnitsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetUnitsByUserResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetUnitsByUser(CAESDO.Catbert.Test.CatbertService.GetUnitsByUserRequest request) {
            return base.Channel.GetUnitsByUser(request);
        }
        
        public CAESDO.Catbert.Test.CatbertService.ServiceUnit[] GetUnitsByUser(string login) {
            CAESDO.Catbert.Test.CatbertService.GetUnitsByUserRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetUnitsByUserRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.GetUnitsByUserRequestBody();
            inValue.Body.login = login;
            CAESDO.Catbert.Test.CatbertService.GetUnitsByUserResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetUnitsByUser(inValue);
            return retVal.Body.GetUnitsByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetRolesResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetRoles(CAESDO.Catbert.Test.CatbertService.GetRolesRequest request) {
            return base.Channel.GetRoles(request);
        }
        
        public CAESDO.Catbert.Test.CatbertService.ServiceRole[] GetRoles(string application) {
            CAESDO.Catbert.Test.CatbertService.GetRolesRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetRolesRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.GetRolesRequestBody();
            inValue.Body.application = application;
            CAESDO.Catbert.Test.CatbertService.GetRolesResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetRoles(inValue);
            return retVal.Body.GetRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetRolesByUserResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetRolesByUser(CAESDO.Catbert.Test.CatbertService.GetRolesByUserRequest request) {
            return base.Channel.GetRolesByUser(request);
        }
        
        public CAESDO.Catbert.Test.CatbertService.ServiceRole[] GetRolesByUser(string application, string login) {
            CAESDO.Catbert.Test.CatbertService.GetRolesByUserRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetRolesByUserRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.GetRolesByUserRequestBody();
            inValue.Body.application = application;
            inValue.Body.login = login;
            CAESDO.Catbert.Test.CatbertService.GetRolesByUserResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetRolesByUser(inValue);
            return retVal.Body.GetRolesByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetUsersByApplication(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRequest request) {
            return base.Channel.GetUsersByApplication(request);
        }
        
        public CAESDO.Catbert.Test.CatbertService.CatbertUser[] GetUsersByApplication(string application) {
            CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRequestBody();
            inValue.Body.application = application;
            CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetUsersByApplication(inValue);
            return retVal.Body.GetUsersByApplicationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetUsersByApplicationRole(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleRequest request) {
            return base.Channel.GetUsersByApplicationRole(request);
        }
        
        public CAESDO.Catbert.Test.CatbertService.CatbertUser[] GetUsersByApplicationRole(string application, string role) {
            CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleRequestBody();
            inValue.Body.application = application;
            inValue.Body.role = role;
            CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetUsersByApplicationRole(inValue);
            return retVal.Body.GetUsersByApplicationRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.SetEmailResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.SetEmail(CAESDO.Catbert.Test.CatbertService.SetEmailRequest request) {
            return base.Channel.SetEmail(request);
        }
        
        public bool SetEmail(string login, string emailAddress) {
            CAESDO.Catbert.Test.CatbertService.SetEmailRequest inValue = new CAESDO.Catbert.Test.CatbertService.SetEmailRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.SetEmailRequestBody();
            inValue.Body.login = login;
            inValue.Body.emailAddress = emailAddress;
            CAESDO.Catbert.Test.CatbertService.SetEmailResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).SetEmail(inValue);
            return retVal.Body.SetEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.SetPhoneNumberResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.SetPhoneNumber(CAESDO.Catbert.Test.CatbertService.SetPhoneNumberRequest request) {
            return base.Channel.SetPhoneNumber(request);
        }
        
        public bool SetPhoneNumber(string login, string phoneNumber) {
            CAESDO.Catbert.Test.CatbertService.SetPhoneNumberRequest inValue = new CAESDO.Catbert.Test.CatbertService.SetPhoneNumberRequest();
            inValue.Body = new CAESDO.Catbert.Test.CatbertService.SetPhoneNumberRequestBody();
            inValue.Body.login = login;
            inValue.Body.phoneNumber = phoneNumber;
            CAESDO.Catbert.Test.CatbertService.SetPhoneNumberResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).SetPhoneNumber(inValue);
            return retVal.Body.SetPhoneNumberResult;
        }
    }
}
