//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAESDO.Catbert.Test.CatbertService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="CAESDO.Services", ConfigurationName="CatbertService.CatbertWebServiceSoap")]
    public interface CatbertWebServiceSoap {
        
        // CODEGEN: Generating message contract since message SearchNewUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/SearchNewUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.SearchNewUserResponse SearchNewUser(CAESDO.Catbert.Test.CatbertService.SearchNewUserRequest request);
        
        // CODEGEN: Generating message contract since message InsertNewUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/InsertNewUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.InsertNewUserResponse InsertNewUser(CAESDO.Catbert.Test.CatbertService.InsertNewUserRequest request);
        
        // CODEGEN: Generating message contract since message VerifyUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/VerifyUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.VerifyUserResponse VerifyUser(CAESDO.Catbert.Test.CatbertService.VerifyUserRequest request);
        
        // CODEGEN: Generating message contract since message AssignPermissionsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/AssignPermissions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.AssignPermissionsResponse AssignPermissions(CAESDO.Catbert.Test.CatbertService.AssignPermissionsRequest request);
        
        // CODEGEN: Generating message contract since message DeletePermissionsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/DeletePermissions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.DeletePermissionsResponse DeletePermissions(CAESDO.Catbert.Test.CatbertService.DeletePermissionsRequest request);
        
        // CODEGEN: Generating message contract since message PermissionExistsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/PermissionExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.PermissionExistsResponse PermissionExists(CAESDO.Catbert.Test.CatbertService.PermissionExistsRequest request);
        
        // CODEGEN: Generating message contract since message AddUnitRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/AddUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.AddUnitResponse AddUnit(CAESDO.Catbert.Test.CatbertService.AddUnitRequest request);
        
        // CODEGEN: Generating message contract since message DeleteUnitRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/DeleteUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.DeleteUnitResponse DeleteUnit(CAESDO.Catbert.Test.CatbertService.DeleteUnitRequest request);
        
        // CODEGEN: Generating message contract since message GetUnitsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetUnits", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.GetUnitsResponse GetUnits(CAESDO.Catbert.Test.CatbertService.GetUnitsRequest request);
        
        // CODEGEN: Generating message contract since message GetUnitsByUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetUnitsByUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.GetUnitsByUserResponse GetUnitsByUser(CAESDO.Catbert.Test.CatbertService.GetUnitsByUserRequest request);
        
        // CODEGEN: Generating message contract since message GetRolesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetRoles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.GetRolesResponse GetRoles(CAESDO.Catbert.Test.CatbertService.GetRolesRequest request);
        
        // CODEGEN: Generating message contract since message GetRolesByUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetRolesByUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.GetRolesByUserResponse GetRolesByUser(CAESDO.Catbert.Test.CatbertService.GetRolesByUserRequest request);
        
        // CODEGEN: Generating message contract since message GetUsersByApplicationRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetUsersByApplication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationResponse GetUsersByApplication(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRequest request);
        
        // CODEGEN: Generating message contract since message GetUsersByApplicationRoleRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/GetUsersByApplicationRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleResponse GetUsersByApplicationRole(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleRequest request);
        
        // CODEGEN: Generating message contract since message AddEmailRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/AddEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.AddEmailResponse AddEmail(CAESDO.Catbert.Test.CatbertService.AddEmailRequest request);
        
        // CODEGEN: Generating message contract since message AddPhoneNumberRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="CAESDO.Services/AddPhoneNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CAESDO.Catbert.Test.CatbertService.AddPhoneNumberResponse AddPhoneNumber(CAESDO.Catbert.Test.CatbertService.AddPhoneNumberRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    public partial class SecurityContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIDField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    public partial class ServiceUnit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string unitFISField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UnitFIS {
            get {
                return this.unitFISField;
            }
            set {
                this.unitFISField = value;
                this.RaisePropertyChanged("UnitFIS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    public partial class ServiceRole : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatbertUser))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    public partial class ServiceUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string employeeIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string loginField;
        
        private string emailField;
        
        private string departmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CAESDO.Services")]
    public partial class CatbertUser : ServiceUser {
        
        private int userIDField;
        
        private ServiceRole[] rolesField;
        
        private ServiceUnit[] unitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public ServiceRole[] Roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
                this.RaisePropertyChanged("Roles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public ServiceUnit[] Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
                this.RaisePropertyChanged("Units");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchNewUser", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class SearchNewUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string eid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=1)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=2)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=3)]
        public string login;
        
        public SearchNewUserRequest() {
        }
        
        public SearchNewUserRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string eid, string firstName, string lastName, string login) {
            this.SecurityContext = SecurityContext;
            this.eid = eid;
            this.firstName = firstName;
            this.lastName = lastName;
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchNewUserResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class SearchNewUserResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public ServiceUser[] SearchNewUserResult;
        
        public SearchNewUserResponse() {
        }
        
        public SearchNewUserResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, ServiceUser[] SearchNewUserResult) {
            this.SecurityContext = SecurityContext;
            this.SearchNewUserResult = SearchNewUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertNewUser", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class InsertNewUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public CAESDO.Catbert.Test.CatbertService.ServiceUser serviceUser;
        
        public InsertNewUserRequest() {
        }
        
        public InsertNewUserRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, CAESDO.Catbert.Test.CatbertService.ServiceUser serviceUser) {
            this.SecurityContext = SecurityContext;
            this.serviceUser = serviceUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertNewUserResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class InsertNewUserResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public int InsertNewUserResult;
        
        public InsertNewUserResponse() {
        }
        
        public InsertNewUserResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, int InsertNewUserResult) {
            this.SecurityContext = SecurityContext;
            this.InsertNewUserResult = InsertNewUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyUser", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class VerifyUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string login;
        
        public VerifyUserRequest() {
        }
        
        public VerifyUserRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login) {
            this.SecurityContext = SecurityContext;
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyUserResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class VerifyUserResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public bool VerifyUserResult;
        
        public VerifyUserResponse() {
        }
        
        public VerifyUserResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, bool VerifyUserResult) {
            this.SecurityContext = SecurityContext;
            this.VerifyUserResult = VerifyUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignPermissions", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class AssignPermissionsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=1)]
        public string application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=2)]
        public string role;
        
        public AssignPermissionsRequest() {
        }
        
        public AssignPermissionsRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string application, string role) {
            this.SecurityContext = SecurityContext;
            this.login = login;
            this.application = application;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignPermissionsResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class AssignPermissionsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public bool AssignPermissionsResult;
        
        public AssignPermissionsResponse() {
        }
        
        public AssignPermissionsResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, bool AssignPermissionsResult) {
            this.SecurityContext = SecurityContext;
            this.AssignPermissionsResult = AssignPermissionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePermissions", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class DeletePermissionsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=1)]
        public string application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=2)]
        public string role;
        
        public DeletePermissionsRequest() {
        }
        
        public DeletePermissionsRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string application, string role) {
            this.SecurityContext = SecurityContext;
            this.login = login;
            this.application = application;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePermissionsResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class DeletePermissionsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public bool DeletePermissionsResult;
        
        public DeletePermissionsResponse() {
        }
        
        public DeletePermissionsResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, bool DeletePermissionsResult) {
            this.SecurityContext = SecurityContext;
            this.DeletePermissionsResult = DeletePermissionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PermissionExists", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class PermissionExistsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=1)]
        public string application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=2)]
        public string role;
        
        public PermissionExistsRequest() {
        }
        
        public PermissionExistsRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string application, string role) {
            this.SecurityContext = SecurityContext;
            this.login = login;
            this.application = application;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PermissionExistsResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class PermissionExistsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public bool PermissionExistsResult;
        
        public PermissionExistsResponse() {
        }
        
        public PermissionExistsResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, bool PermissionExistsResult) {
            this.SecurityContext = SecurityContext;
            this.PermissionExistsResult = PermissionExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUnit", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class AddUnitRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=1)]
        public string unitFIS;
        
        public AddUnitRequest() {
        }
        
        public AddUnitRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string unitFIS) {
            this.SecurityContext = SecurityContext;
            this.login = login;
            this.unitFIS = unitFIS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUnitResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class AddUnitResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public bool AddUnitResult;
        
        public AddUnitResponse() {
        }
        
        public AddUnitResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, bool AddUnitResult) {
            this.SecurityContext = SecurityContext;
            this.AddUnitResult = AddUnitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUnit", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class DeleteUnitRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=1)]
        public string unitFIS;
        
        public DeleteUnitRequest() {
        }
        
        public DeleteUnitRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string unitFIS) {
            this.SecurityContext = SecurityContext;
            this.login = login;
            this.unitFIS = unitFIS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUnitResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class DeleteUnitResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public bool DeleteUnitResult;
        
        public DeleteUnitResponse() {
        }
        
        public DeleteUnitResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, bool DeleteUnitResult) {
            this.SecurityContext = SecurityContext;
            this.DeleteUnitResult = DeleteUnitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnits", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetUnitsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        public GetUnitsRequest() {
        }
        
        public GetUnitsRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext) {
            this.SecurityContext = SecurityContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnitsResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetUnitsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public ServiceUnit[] GetUnitsResult;
        
        public GetUnitsResponse() {
        }
        
        public GetUnitsResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, ServiceUnit[] GetUnitsResult) {
            this.SecurityContext = SecurityContext;
            this.GetUnitsResult = GetUnitsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnitsByUser", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetUnitsByUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string login;
        
        public GetUnitsByUserRequest() {
        }
        
        public GetUnitsByUserRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login) {
            this.SecurityContext = SecurityContext;
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnitsByUserResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetUnitsByUserResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public ServiceUnit[] GetUnitsByUserResult;
        
        public GetUnitsByUserResponse() {
        }
        
        public GetUnitsByUserResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, ServiceUnit[] GetUnitsByUserResult) {
            this.SecurityContext = SecurityContext;
            this.GetUnitsByUserResult = GetUnitsByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRoles", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetRolesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string application;
        
        public GetRolesRequest() {
        }
        
        public GetRolesRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string application) {
            this.SecurityContext = SecurityContext;
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRolesResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetRolesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public ServiceRole[] GetRolesResult;
        
        public GetRolesResponse() {
        }
        
        public GetRolesResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, ServiceRole[] GetRolesResult) {
            this.SecurityContext = SecurityContext;
            this.GetRolesResult = GetRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRolesByUser", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetRolesByUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=1)]
        public string login;
        
        public GetRolesByUserRequest() {
        }
        
        public GetRolesByUserRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string application, string login) {
            this.SecurityContext = SecurityContext;
            this.application = application;
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRolesByUserResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetRolesByUserResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public ServiceRole[] GetRolesByUserResult;
        
        public GetRolesByUserResponse() {
        }
        
        public GetRolesByUserResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, ServiceRole[] GetRolesByUserResult) {
            this.SecurityContext = SecurityContext;
            this.GetRolesByUserResult = GetRolesByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersByApplication", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetUsersByApplicationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string application;
        
        public GetUsersByApplicationRequest() {
        }
        
        public GetUsersByApplicationRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string application) {
            this.SecurityContext = SecurityContext;
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersByApplicationResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetUsersByApplicationResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public CatbertUser[] GetUsersByApplicationResult;
        
        public GetUsersByApplicationResponse() {
        }
        
        public GetUsersByApplicationResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, CatbertUser[] GetUsersByApplicationResult) {
            this.SecurityContext = SecurityContext;
            this.GetUsersByApplicationResult = GetUsersByApplicationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersByApplicationRole", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetUsersByApplicationRoleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string application;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=1)]
        public string role;
        
        public GetUsersByApplicationRoleRequest() {
        }
        
        public GetUsersByApplicationRoleRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string application, string role) {
            this.SecurityContext = SecurityContext;
            this.application = application;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersByApplicationRoleResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class GetUsersByApplicationRoleResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public CatbertUser[] GetUsersByApplicationRoleResult;
        
        public GetUsersByApplicationRoleResponse() {
        }
        
        public GetUsersByApplicationRoleResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, CatbertUser[] GetUsersByApplicationRoleResult) {
            this.SecurityContext = SecurityContext;
            this.GetUsersByApplicationRoleResult = GetUsersByApplicationRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddEmail", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class AddEmailRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=1)]
        public string emailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=2)]
        public int emailTypeID;
        
        public AddEmailRequest() {
        }
        
        public AddEmailRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string emailAddress, int emailTypeID) {
            this.SecurityContext = SecurityContext;
            this.login = login;
            this.emailAddress = emailAddress;
            this.emailTypeID = emailTypeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddEmailResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class AddEmailResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public bool AddEmailResult;
        
        public AddEmailResponse() {
        }
        
        public AddEmailResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, bool AddEmailResult) {
            this.SecurityContext = SecurityContext;
            this.AddEmailResult = AddEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPhoneNumber", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class AddPhoneNumberRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=1)]
        public string phoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=2)]
        public int phoneType;
        
        public AddPhoneNumberRequest() {
        }
        
        public AddPhoneNumberRequest(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string phoneNumber, int phoneType) {
            this.SecurityContext = SecurityContext;
            this.login = login;
            this.phoneNumber = phoneNumber;
            this.phoneType = phoneType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPhoneNumberResponse", WrapperNamespace="CAESDO.Services", IsWrapped=true)]
    public partial class AddPhoneNumberResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CAESDO.Services")]
        public CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CAESDO.Services", Order=0)]
        public bool AddPhoneNumberResult;
        
        public AddPhoneNumberResponse() {
        }
        
        public AddPhoneNumberResponse(CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, bool AddPhoneNumberResult) {
            this.SecurityContext = SecurityContext;
            this.AddPhoneNumberResult = AddPhoneNumberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface CatbertWebServiceSoapChannel : CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CatbertWebServiceSoapClient : System.ServiceModel.ClientBase<CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap>, CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap {
        
        public CatbertWebServiceSoapClient() {
        }
        
        public CatbertWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatbertWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatbertWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatbertWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.SearchNewUserResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.SearchNewUser(CAESDO.Catbert.Test.CatbertService.SearchNewUserRequest request) {
            return base.Channel.SearchNewUser(request);
        }
        
        public ServiceUser[] SearchNewUser(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string eid, string firstName, string lastName, string login) {
            CAESDO.Catbert.Test.CatbertService.SearchNewUserRequest inValue = new CAESDO.Catbert.Test.CatbertService.SearchNewUserRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.eid = eid;
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.login = login;
            CAESDO.Catbert.Test.CatbertService.SearchNewUserResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).SearchNewUser(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.SearchNewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.InsertNewUserResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.InsertNewUser(CAESDO.Catbert.Test.CatbertService.InsertNewUserRequest request) {
            return base.Channel.InsertNewUser(request);
        }
        
        public int InsertNewUser(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, CAESDO.Catbert.Test.CatbertService.ServiceUser serviceUser) {
            CAESDO.Catbert.Test.CatbertService.InsertNewUserRequest inValue = new CAESDO.Catbert.Test.CatbertService.InsertNewUserRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.serviceUser = serviceUser;
            CAESDO.Catbert.Test.CatbertService.InsertNewUserResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).InsertNewUser(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.InsertNewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.VerifyUserResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.VerifyUser(CAESDO.Catbert.Test.CatbertService.VerifyUserRequest request) {
            return base.Channel.VerifyUser(request);
        }
        
        public bool VerifyUser(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login) {
            CAESDO.Catbert.Test.CatbertService.VerifyUserRequest inValue = new CAESDO.Catbert.Test.CatbertService.VerifyUserRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.login = login;
            CAESDO.Catbert.Test.CatbertService.VerifyUserResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).VerifyUser(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.VerifyUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.AssignPermissionsResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.AssignPermissions(CAESDO.Catbert.Test.CatbertService.AssignPermissionsRequest request) {
            return base.Channel.AssignPermissions(request);
        }
        
        public bool AssignPermissions(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string application, string role) {
            CAESDO.Catbert.Test.CatbertService.AssignPermissionsRequest inValue = new CAESDO.Catbert.Test.CatbertService.AssignPermissionsRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.login = login;
            inValue.application = application;
            inValue.role = role;
            CAESDO.Catbert.Test.CatbertService.AssignPermissionsResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).AssignPermissions(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.AssignPermissionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.DeletePermissionsResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.DeletePermissions(CAESDO.Catbert.Test.CatbertService.DeletePermissionsRequest request) {
            return base.Channel.DeletePermissions(request);
        }
        
        public bool DeletePermissions(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string application, string role) {
            CAESDO.Catbert.Test.CatbertService.DeletePermissionsRequest inValue = new CAESDO.Catbert.Test.CatbertService.DeletePermissionsRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.login = login;
            inValue.application = application;
            inValue.role = role;
            CAESDO.Catbert.Test.CatbertService.DeletePermissionsResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).DeletePermissions(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.DeletePermissionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.PermissionExistsResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.PermissionExists(CAESDO.Catbert.Test.CatbertService.PermissionExistsRequest request) {
            return base.Channel.PermissionExists(request);
        }
        
        public bool PermissionExists(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string application, string role) {
            CAESDO.Catbert.Test.CatbertService.PermissionExistsRequest inValue = new CAESDO.Catbert.Test.CatbertService.PermissionExistsRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.login = login;
            inValue.application = application;
            inValue.role = role;
            CAESDO.Catbert.Test.CatbertService.PermissionExistsResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).PermissionExists(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.PermissionExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.AddUnitResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.AddUnit(CAESDO.Catbert.Test.CatbertService.AddUnitRequest request) {
            return base.Channel.AddUnit(request);
        }
        
        public bool AddUnit(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string unitFIS) {
            CAESDO.Catbert.Test.CatbertService.AddUnitRequest inValue = new CAESDO.Catbert.Test.CatbertService.AddUnitRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.login = login;
            inValue.unitFIS = unitFIS;
            CAESDO.Catbert.Test.CatbertService.AddUnitResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).AddUnit(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.AddUnitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.DeleteUnitResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.DeleteUnit(CAESDO.Catbert.Test.CatbertService.DeleteUnitRequest request) {
            return base.Channel.DeleteUnit(request);
        }
        
        public bool DeleteUnit(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string unitFIS) {
            CAESDO.Catbert.Test.CatbertService.DeleteUnitRequest inValue = new CAESDO.Catbert.Test.CatbertService.DeleteUnitRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.login = login;
            inValue.unitFIS = unitFIS;
            CAESDO.Catbert.Test.CatbertService.DeleteUnitResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).DeleteUnit(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.DeleteUnitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetUnitsResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetUnits(CAESDO.Catbert.Test.CatbertService.GetUnitsRequest request) {
            return base.Channel.GetUnits(request);
        }
        
        public ServiceUnit[] GetUnits(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext) {
            CAESDO.Catbert.Test.CatbertService.GetUnitsRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetUnitsRequest();
            inValue.SecurityContext = SecurityContext;
            CAESDO.Catbert.Test.CatbertService.GetUnitsResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetUnits(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.GetUnitsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetUnitsByUserResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetUnitsByUser(CAESDO.Catbert.Test.CatbertService.GetUnitsByUserRequest request) {
            return base.Channel.GetUnitsByUser(request);
        }
        
        public ServiceUnit[] GetUnitsByUser(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login) {
            CAESDO.Catbert.Test.CatbertService.GetUnitsByUserRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetUnitsByUserRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.login = login;
            CAESDO.Catbert.Test.CatbertService.GetUnitsByUserResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetUnitsByUser(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.GetUnitsByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetRolesResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetRoles(CAESDO.Catbert.Test.CatbertService.GetRolesRequest request) {
            return base.Channel.GetRoles(request);
        }
        
        public ServiceRole[] GetRoles(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string application) {
            CAESDO.Catbert.Test.CatbertService.GetRolesRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetRolesRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.application = application;
            CAESDO.Catbert.Test.CatbertService.GetRolesResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetRoles(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.GetRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetRolesByUserResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetRolesByUser(CAESDO.Catbert.Test.CatbertService.GetRolesByUserRequest request) {
            return base.Channel.GetRolesByUser(request);
        }
        
        public ServiceRole[] GetRolesByUser(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string application, string login) {
            CAESDO.Catbert.Test.CatbertService.GetRolesByUserRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetRolesByUserRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.application = application;
            inValue.login = login;
            CAESDO.Catbert.Test.CatbertService.GetRolesByUserResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetRolesByUser(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.GetRolesByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetUsersByApplication(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRequest request) {
            return base.Channel.GetUsersByApplication(request);
        }
        
        public CatbertUser[] GetUsersByApplication(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string application) {
            CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.application = application;
            CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetUsersByApplication(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.GetUsersByApplicationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.GetUsersByApplicationRole(CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleRequest request) {
            return base.Channel.GetUsersByApplicationRole(request);
        }
        
        public CatbertUser[] GetUsersByApplicationRole(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string application, string role) {
            CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleRequest inValue = new CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.application = application;
            inValue.role = role;
            CAESDO.Catbert.Test.CatbertService.GetUsersByApplicationRoleResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).GetUsersByApplicationRole(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.GetUsersByApplicationRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.AddEmailResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.AddEmail(CAESDO.Catbert.Test.CatbertService.AddEmailRequest request) {
            return base.Channel.AddEmail(request);
        }
        
        public bool AddEmail(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string emailAddress, int emailTypeID) {
            CAESDO.Catbert.Test.CatbertService.AddEmailRequest inValue = new CAESDO.Catbert.Test.CatbertService.AddEmailRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.login = login;
            inValue.emailAddress = emailAddress;
            inValue.emailTypeID = emailTypeID;
            CAESDO.Catbert.Test.CatbertService.AddEmailResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).AddEmail(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.AddEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CAESDO.Catbert.Test.CatbertService.AddPhoneNumberResponse CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap.AddPhoneNumber(CAESDO.Catbert.Test.CatbertService.AddPhoneNumberRequest request) {
            return base.Channel.AddPhoneNumber(request);
        }
        
        public bool AddPhoneNumber(ref CAESDO.Catbert.Test.CatbertService.SecurityContext SecurityContext, string login, string phoneNumber, int phoneType) {
            CAESDO.Catbert.Test.CatbertService.AddPhoneNumberRequest inValue = new CAESDO.Catbert.Test.CatbertService.AddPhoneNumberRequest();
            inValue.SecurityContext = SecurityContext;
            inValue.login = login;
            inValue.phoneNumber = phoneNumber;
            inValue.phoneType = phoneType;
            CAESDO.Catbert.Test.CatbertService.AddPhoneNumberResponse retVal = ((CAESDO.Catbert.Test.CatbertService.CatbertWebServiceSoap)(this)).AddPhoneNumber(inValue);
            SecurityContext = retVal.SecurityContext;
            return retVal.AddPhoneNumberResult;
        }
    }
}
