ALTER TABLE [dbo].[ApplicationRoles]
    ADD CONSTRAINT [PK_ApplicationRoles] PRIMARY KEY CLUSTERED ([ApplicationRoleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

