ALTER TABLE [dbo].[Schools]
    ADD CONSTRAINT [PK_Schools] PRIMARY KEY CLUSTERED ([SchoolCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

