ALTER TABLE [dbo].[TrackingTypes]
    ADD CONSTRAINT [PK_TrackingType] PRIMARY KEY CLUSTERED ([TrackingTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

