ALTER TABLE [dbo].[UnitAssociations]
    ADD CONSTRAINT [PK_UnitAssociations] PRIMARY KEY CLUSTERED ([UnitAssociationID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

